### ISSUE TITLE
"CustomerKey is not defined" error in Chrome browser when editing appointment

### ISSUE THREAD

**Issue by wetzf** [RotherOSS/AppointmentToTicket#1]
When opening an existing appointment with ticket creation the following error appears in the browser console. As a result it is not possible to use the save, copy, delete or cancel buttons in the popup window. They just do nothing. 

![Bild](https://github.com/RotherOSS/AppointmentToTicket/assets/84456263/42519cb2-2355-4834-bcc9-2d1bd497404b)

This seems to only happen in Chrome and chromebased browsers. In Firefox it works fine.

As a workaround I changed the line 1470 in _var/httpd/htdocs/js/Core.Agent.AppointmentCalendar.js_ as follows. Which for us works in Chrome and Firefox, but may not be the best solution as _CustomerKey_ is already defined some lines earlier. 

`let CustomerKey = $('#CustomerKey_' +$(this).val()).val();`

![grafik](https://github.com/RotherOSS/AppointmentToTicket/assets/84456263/8f97a301-490c-428e-8100-1868661de441)

**Comment by stefanhaerter** [comment]
This might already have been solved with https://github.com/RotherOSS/otobo/issues/3803 - I will try to confirm it anytime soon.

**Comment by stefanhaerter** [comment]
Reproduced in Chrome.

**Comment by stefanhaerter** [comment]
The scoping and initialization of the CustomerKey variable were broken. Pushed the fix - closing the issue.
